In [1]:
import tensorflow as tf
import numpy as np

A = tf.constant([[1.,2.],[3.,4.]])
B = tf.constant([[5.,6.],[7.,8.]])

print(A.numpy())
print(tf.random.uniform(shape=(5,5,3)))
print(np.random.rand(5,5,3))

[[1. 2.]
 [3. 4.]]
tf.Tensor(
[[[0.65549684 0.30970418 0.6644145 ]
  [0.7458348  0.6834377  0.7379731 ]
  [0.03750563 0.02647579 0.439008  ]
  [0.40992975 0.2945497  0.603933  ]
  [0.17480922 0.42748833 0.01652491]]

 [[0.26075637 0.82340014 0.23693097]
  [0.5379449  0.30879295 0.7381842 ]
  [0.8386977  0.17148733 0.50485075]
  [0.46805954 0.6077285  0.80401325]
  [0.78110445 0.2791108  0.44473028]]

 [[0.01298785 0.20737648 0.04326224]
  [0.7856108  0.17965925 0.07561553]
  [0.3049196  0.52656114 0.26348078]
  [0.50224376 0.3857324  0.73769724]
  [0.38694763 0.45538747 0.83597744]]

 [[0.8217813  0.5104097  0.14507365]
  [0.4898671  0.19351304 0.38726008]
  [0.6394415  0.31506193 0.37375128]
  [0.65288556 0.13110971 0.00226867]
  [0.6540009  0.9585279  0.8350661 ]]

 [[0.986336   0.8594012  0.9894074 ]
  [0.32418013 0.2638557  0.36573768]
  [0.8002938  0.962095   0.61289763]
  [0.38835692 0.99466765 0.8987932 ]
  [0.00210381 0.47045624 0.93964326]]], shape=(5, 5, 3), dtype=float32)
[[

In [2]:
import tensorflow as tf

x = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
    y = tf.square(x)
y_grad = tape.gradient(y,x)
print([y,y_grad])

[<tf.Tensor: shape=(), dtype=float32, numpy=9.0>, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>]


In [3]:
import tensorflow as tf

X = tf.constant([[1.,2.],[3.,4.]])
y = tf.constant([1.,2.])

w = tf.Variable(initial_value = [1.,2.])
b = tf.Variable(initial_value = [1.])

with tf.GradientTape() as tape:
    L = 0.5*tf.reduce_sum(tf.matmul(X,w)+b)

InvalidArgumentError: In[1] is not a matrix. Instead it has shape [2] [Op:MatMul]